# Site settings
title: Anne Bozack
email: anne.bozack@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Academic website for Anne Bozack.
baseurl: "/docs" # the subpath of your site, e.g. /blog/
url: "http://annebozack.github.io" # the base hostname & protocol for your site
twitter_username: annebozack
github_username:  annebozack

theme: pages-themes/minimal
